theme = "tokyonight"

[editor]
bufferline = "always"
cursorline = true
idle-timeout = 200
mouse=true

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection" , "keep_primary_selection"]
"A-j" = ["goto_line_end","extend_line_below","delete_selection", "paste_after"]
"A-k" = ["goto_line_end","extend_line_below","delete_selection", "move_line_up","paste_before"]
"C-j" = ["half_page_down"]
"C-k" = ["half_page_up"]

[keys.insert]
C-l = "move_char_right"

[keys.normal.backspace]
d = "goto_next_diag"
D = "goto_prev_diag"
q = ":bc"
r = ":sh cargo run"
t = ":sh wt -d ."
v = ["wonly", "vsplit", "goto_definition"]
