theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "always"
cursorline = true
idle-timeout = 200
mouse=false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection" , "keep_primary_selection"]
"A-j" = ["goto_line_end","extend_line_below","delete_selection", "paste_after"]
"A-k" = ["goto_line_end","extend_line_below","delete_selection", "move_line_up","paste_before"]

[keys.insert]
C-l = "move_char_right"

[keys.normal.backspace]
d = "goto_next_diag"
D = "goto_prev_diag"
a = "goto_next_parameter"
A = "goto_prev_parameter"
q = ":bc"
r = ":run-shell-command cargo run"

